### ISSUE TITLE
 CORS policy Issue 

### ISSUE THREAD

**Issue by reverie-ss** [bebo925/ng-thermal-print#1]
The below error shows up when i try to connect using the network.

Access to XMLHttpRequest at 'http://192.168.1.12/StarWebPRNT/SendMessage' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

**Comment by einerb** [comment]
Hello,
I also have the same inconvenience when placing a different ip.
I hope you can help me!
Thank you

**Comment by bebo925** [comment]
I believe you have to use https to avoid the CORS issue.  
So, you will need to serve your angular app using https and you will need to create and download a certificate from the WebPrnt capable Star printer. Here is Star's manual on doing that: [http://www.starmicronics.com/support/Mannualfolder/en/_sampleProgram.htm#sampleProgramConcept](url)
