### ISSUE TITLE
i cannot see printer names on windows 10

### ISSUE THREAD

**Issue by fatihpolatli** [bebo925/ng-thermal-print#10]
hi,

i can see the printer names on chrome on mac but i cannot see on windows, here is screenshot. any ideas?

[![image](https://i.hizliresim.com/mX0B10.png)](https://hizliresim.com/mX0B10)

**Comment by bebo925** [comment]
@fatihpolatli 
You have to visit chrome://flags and enable the flag for WebUSB.
