### ISSUE TITLE
Not connected to printer.

### ISSUE THREAD

**Issue by omwro** [bebo925/ng-thermal-print#11]
Hey man, i have a small problem and would like to know if u have a solution for my problem. I've a Star tsp100 and trying to print it with angular 8. i have all types or drivers installed and webusb enabled. it even says connected within the webusb popup and able to print with the chrome dialog. but cant make connection with the code. any idea why? thanks in advance

webusb popup screenshot: http://prntscr.com/qd5x41

Console log screenshot: http://prntscr.com/qd5xjw

**Comment by bebo925** [comment]
Are you on a Windows machine?  I found that when Windows installs the driver, it claims the interface and doesn't allow other devices to claim it.  You have to use the WinUSB driver.  I used a program called Zadig [https://zadig.akeo.ie](url)  to swap the drivers out successfully.

**Comment by omwro** [comment]
Hey Bebo, 
Installing custom drivers did fix it and it got recognized by starprnt but if I press print(), it does nothing. could it be because print() asked for a PrintDriver as parameter but doesnt get it from the html button, or maybe if it did get a PrintDriver as parameter, it isn't used within the print() method. thanks in advance.

**Comment by bebo925** [comment]
You will have to probably share some code at this point in order to problem solve.

**Comment by omwro** [comment]
I literally have the same code as the readme but just for proof:

Typescript:
`
import { Component, OnInit } from '@angular/core';
import {PrintDriver} from 'ng-thermal-print/lib/drivers/PrintDriver';
import {PrintService, UsbDriver, WebPrintDriver} from 'ng-thermal-print';

@Component({
  selector: 'app-testrealm',
  templateUrl: './testrealm.component.html',
  styleUrls: ['./testrealm.component.css']
})
export class TestrealmComponent implements OnInit {
  ngOnInit() {}

  status: boolean = false;
  usbPrintDriver: UsbDriver;
  webPrintDriver: WebPrintDriver;
  ip: string = '';

  constructor(private printService: PrintService) {
    this.usbPrintDriver = new UsbDriver();
    this.printService.isConnected.subscribe(result => {
      this.status = result;
      if (result) {
        console.log('Connected to printer!!!');
      } else {
        console.log('Not connected to printer.');
      }
    });
  }

  requestUsb() {
    this.usbPrintDriver.requestUsb().subscribe(result => {
      this.printService.setDriver(this.usbPrintDriver, 'ESC/POS');
    });
  }

  connectToWebPrint() {
    this.webPrintDriver = new WebPrintDriver(this.ip);
    this.printService.setDriver(this.webPrintDriver, 'WebPRNT');
  }

  print(driver: PrintDriver) {
    this.printService.init()
      .setBold(true)
      .writeLine('Hello World!')
      .setBold(false)
      .feed(4)
      .cut('full')
      .flush();
  }
}
`

HTML:
`
<h1>Test Realm</h1>
<strong>Status: {{status}}</strong>
<div>
  <input [(ngModel)]="ip" type="text" name="ip" placeholder="IP of printer with WebPRNT">
  <button (click)="connectToWebPrint()">Connect to WebPRNT</button>
</div>

<div>
  <button (click)="requestUsb()">Connect to USB</button>
</div>

<div>
  <button (click)="print()" [disabled]="status === false">Print !</button>
</div>
`

appmodule:
`
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import { NavbarComponent } from './navbar/navbar.component';
import { ContentComponent } from './content/content.component';
import { WegbrengenheaderComponent } from './content/wegbrengen/wegbrengenheader/wegbrengenheader.component';
import { WegbrengenproductComponent } from './content/wegbrengen/wegbrengenproduct/wegbrengenproduct.component';
import { WegbrengencontentComponent } from './content/wegbrengen/wegbrengencontent/wegbrengencontent.component';
import { HttpClientModule} from '@angular/common/http';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import {FormsModule, ReactiveFormsModule} from '@angular/forms';
import { OphalenheaderComponent } from './content/ophalen/ophalenheader/ophalenheader.component';
import { OphalencontentComponent } from './content/ophalen/ophalencontent/ophalencontent.component';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { TestrealmComponent } from './content/testrealm/testrealm.component';
import {ThermalPrintModule} from 'ng-thermal-print';

@NgModule({
  declarations: [
    AppComponent,
    NavbarComponent,
    ContentComponent,
    WegbrengenheaderComponent,
    WegbrengenproductComponent,
    WegbrengencontentComponent,
    OphalenheaderComponent,
    OphalencontentComponent,
    TestrealmComponent,
  ],
  imports: [
    BrowserModule,
    HttpClientModule,
    FontAwesomeModule,
    FormsModule,
    NgbModule,
    ReactiveFormsModule,
    ThermalPrintModule,
  ],
  exports: [],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
`
ask me any time if you have to see more code or results

**Comment by bebo925** [comment]
@omwro Are you able to test this on a non-Windows device (Chromebook or Mac)?  I feel as though it is OS driver related.

**Comment by omwro** [comment]
@bebo925 I currently have no other test enviroment other than windows 10. i do have tried it on other windows machines but still the same result. could it be that my Star tsp100(143IIU) needs to allow any settings first to communicate with your library? Thanks again for taking time to solve this.

**Comment by bebo925** [comment]
@omwro Which driver did you use with Zidag?

**Comment by GNorbi** [comment]
@omwro Did you solved the problem? I have the same device, with the same problem.. Thank you.

**Comment by omwro** [comment]
@GNorbi I actually did not. My purpose was to use this as a one-click print solution. It did print in normal windows and chrome print setting but not as a one-click. After contacting my printer provider about it, they said my printer is giving an error and we can't fix it, so i gave up with this solution, thinking it was 1 of the reasons this didnt work. The error i had was a health failure when enabling JavaPOS in the printer software settings. However in case you are also making a web bases POS system. I used the kiosk feature in chrome to auto print my receipts and that did the job. I am closing this issue since it is unknown what the exact reason is and i moved on to another solution.

**Comment by lhmboyz** [comment]
> Are you on a Windows machine? I found that when Windows installs the driver, it claims the interface and doesn't allow other devices to claim it. You have to use the WinUSB driver. I used a program called Zadig [https://zadig.akeo.ie](url) to swap the drivers out successfully.

OMG, thank you, you save my day, i don't have any idea at first why the printer is always not connected on Windows, but it's doing fine on Mac. Zadig solved this issue very clever, thanks.
