### ISSUE TITLE
Error trying ng-thermal-print 

### ISSUE THREAD

**Issue by yaxx** [bebo925/ng-thermal-print#12]
ng-thermal-print.js:1004 Uncaught TypeError: Object(...) is not a function
    at ng-thermal-print.js:1004
    at Object../node_modules/ng-thermal-print/fesm5/ng-thermal-print.js (ng-thermal-print.js:1006)

**Comment by lerg96** [comment]
I have the same error, why is closed this issue? 
Only instaled this package, and added it to app.module.ts -> imports

**Comment by edgarsantiag0** [comment]
I have the same error,
