### ISSUE TITLE
Cannot print barcode in svg format

### ISSUE THREAD

**Issue by alimynn** [bebo925/ng-thermal-print#13]
Is there a feature to print EAN or CODE128 type barcodes in svg format or directly?
Thanks in advance.

**Comment by bebo925** [comment]
@alimynn Not currently.  I haven't had that need, but I think it will be easy to add this functionality.  I would accept pull request.

**Comment by xyrintech** [comment]
I am new using thermal printers. 
Would it be possible to share some thoughts how it can be done?
