### ISSUE TITLE
Not publishing with visual studio

### ISSUE THREAD

**Issue by DCode11** [bebo925/ng-thermal-print#16]
Hi, 
While I am trying to publish ng-thermal-print with visual studio Entity Framework Core (2019), it gives me below error:
1)
The command "npm run build -- --prod" exited with code 1.
2)
ERROR in ../ng-thermal-print/ng-thermal-print.ts(9,2): Error during template compile of 'PrintService'
Could not resolve @angular/core relative to [object Object]..

Please help...
Thanks in advance.

**Comment by bebo925** [comment]
`npm run buld-lib` will build the library.
