### ISSUE TITLE
 Cannot find name 'USBDevice'.

### ISSUE THREAD

**Issue by juanfdooocampo** [bebo925/ng-thermal-print#2]
ERROR in node_modules/ng-thermal-print/lib/drivers/UsbDriver.d.ts(1,23): error TS2688: Cannot find type definition file for 'w3c-web-usb'.
node_modules/ng-thermal-print/lib/drivers/UsbDriver.d.ts(16,30): error TS2304: Cannot find name 'USBDevice'.

**Comment by SouengKimmeng** [comment]
+1

**Comment by bebo925** [comment]
@juanfdooocampo 
Try running `npm install --save @types/w3c-web-usb`
