### ISSUE TITLE
Cannot read property 'requestDevice' of undefined

### ISSUE THREAD

**Issue by lilian131** [bebo925/ng-thermal-print#6]
is there a method to select default printer? 
or put the device-uri
or ipp://***

**Comment by bebo925** [comment]
I have only developed drivers for WEBUSB API or Star's WebPrnt.  So you either have to use a WEBUSB capable browser or one of Star's available web interfaces.

**Comment by sidneiju** [comment]
This error is caused because requestDevice() needs to run using HTTPS or localhost.

Refer: https://developer.mozilla.org/en-US/docs/Web/API/USB/requestDevice
