### ISSUE TITLE
Cannot print with WebprintDriver. error => http://@IpPrinter/StarwebPRNT/SendMessage net::ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by asn96** [bebo925/ng-thermal-print#7]
if i add the port 9100 after the url it print the option.

**Comment by bebo925** [comment]
@asn96 Is your printer configured to listen for the HTTP request commands on a different port?

**Comment by DCode11** [comment]
My printer is configured to listen for the HTTP request commands with the 9100 port, but "Connect to WebPRNT" button not printing on IP based printer!!
Please help.

**Comment by bebo925** [comment]
@DCode11 
Would it happen to be listening on a secure url (https)?  There is a second parameter in the WebPrintDriver that defaults to false.  Set it to true if you need https.

` this.webPrintDriver = new WebPrintDriver(this.ip, true); `

Are you getting any javascript errors in the console?

**Comment by DCode11** [comment]
Hi, 
Thanks for reply.
Yes, I tried with https too,

below are console messages:
"Angular is running in the development mode. Call enableProdMode() to enable the production mode.
test.component.ts:40 DOMException: Must be handling a user gesture to show a permission request.
client:52 [WDS] Live Reloading enabled.
OPTIONS https://192.211.../StarWebPRNT/SendMessage net::ERR_CONNECTION_REFUSED"

**Comment by bebo925** [comment]
Closing due to no response.
