### ISSUE TITLE
Add w3c-web-usb types on README 

### ISSUE THREAD

**Issue by jcfrane** [bebo925/ng-thermal-print#9]
Hi,

Building without installing w3c-web-usb type throws an error.

> ERROR in node_modules/ng-thermal-print/lib/drivers/UsbDriver.d.ts:16:30 - error TS2304: Cannot find name 'USBDevice'.
> 
> 
>    requestUsb(): Observable<USBDevice>;

**Comment by bebo925** [comment]
I think I forgot to save that locally to the project.  I will look at adding that soon.  Thanks!

**Comment by asn96** [comment]
> Hi,
> 
> Building without installing w3c-web-usb type throws an error.
> 
> > ERROR in node_modules/ng-thermal-print/lib/drivers/UsbDriver.d.ts:16:30 - error TS2304: Cannot find name 'USBDevice'.
> > requestUsb(): Observable;

Hello the file UsbDriver.d.ts reference to w3c-web-usb so you must install it with command: npm install @types/w3c-web-usb
